[package]
name = "lexico"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Lexicographically orderable number encodings"
repository = "https://github.com/jabr/lexico"

[lib]
crate-type = ["rlib", "cdylib"]
path = "lexico.rs"
